// AUTO-GENERATED from Open-Paws/no-animal-violence. Do not edit directly.
import { DangerDSLType } from "danger";

declare const danger: DangerDSLType;
declare function warn(message: string): void;
declare function message(message: string): void;

interface NoAnimalViolenceOptions {
  severity?: "warn" | "message";
}

interface Pattern {
  regex: RegExp;
  phrase: string;
  alternatives: string[];
  reason: string;
}

const PATTERNS: Pattern[] = [
  { regex: new RegExp("kill\\s+two\\s+birds\\s+with\\s+one\\s+stone", "gi"), phrase: "kill two birds with one stone", alternatives: ["accomplish two things at once","solve two problems with one action","hit two targets with one shot"], reason: "This phrase frames killing animals as a routine way to solve a problem. Plain alternatives like 'accomplish two things at once' carry the same meaning without invoking harm." },
  { regex: new RegExp("beat(ing)?\\s+a\\s+dead\\s+horse", "gi"), phrase: "beat a dead horse", alternatives: ["belabor the point","go over old ground","repeat unnecessarily"], reason: "This phrase uses an image of striking an animal's body as a metaphor for wasted effort. 'Belabor the point' is clearer and skips the imagery." },
  { regex: new RegExp("(more\\s+than\\s+one|another|different|several)\\s+way[s]?\\s+to\\s+skin\\s+a\\s+cat", "gi"), phrase: "more than one way to skin a cat", alternatives: ["more than one way to peel an orange","multiple approaches available","several ways to do this"], reason: "Cat skinning as a metaphor for having options. 'Multiple approaches available' or 'more than one way to peel an orange' carries the same meaning." },
  { regex: new RegExp("let\\s+the\\s+cat\\s+out\\s+of\\s+the\\s+bag", "gi"), phrase: "let the cat out of the bag", alternatives: ["reveal the secret","disclose prematurely","let it slip"], reason: "Traced to fraudulent livestock markets and implies trapping animals. 'Reveal the secret' says the same thing more directly." },
  { regex: new RegExp("open(ing)?\\s+a\\s+can\\s+of\\s+worms", "gi"), phrase: "open a can of worms", alternatives: ["create a complicated situation","uncover hidden problems","open Pandora's box"], reason: "References worms packaged as live bait to catch and kill fish. 'Open a difficult topic' or 'uncover hidden problems' is more precise." },
  { regex: new RegExp("wild\\s+goose\\s+chase", "gi"), phrase: "wild goose chase", alternatives: ["futile search","pointless pursuit","fool's errand"], reason: "Casts pursuing a living bird as a pointless annoyance. 'Futile search' or 'fool's errand' says the same thing without the hunting framing." },
  { regex: new RegExp("(like\\s+)?shoot(ing)?\\s+fish\\s+in\\s+a\\s+barrel", "gi"), phrase: "shooting fish in a barrel", alternatives: ["trivially easy","a sure thing","no challenge at all"], reason: "Mass-killing imagery used to mean 'easy.' 'Trivially easy' or 'a sure thing' says the same thing without it." },
  { regex: new RegExp("flog(ging)?\\s+a\\s+dead\\s+horse", "gi"), phrase: "flog a dead horse", alternatives: ["belabor the point","waste effort on a settled matter","repeat unnecessarily"], reason: "Describes whipping an animal's corpse — the same image as 'beat a dead horse'. 'Belabor the point' is a direct replacement." },
  { regex: new RegExp("(bigger|other)\\s+fish\\s+to\\s+fry", "gi"), phrase: "bigger fish to fry", alternatives: ["more important matters to address","bigger fish to free"], reason: "Fish-as-food commodification for 'more important things.' 'More important matters' says the same thing." },
  { regex: new RegExp("\\bguinea\\s+pig\\b", "gi"), phrase: "guinea pig", alternatives: ["test subject","first to try","early adopter"], reason: "Refers to using guinea pigs as expendable test subjects in harmful experiments. 'Test subject' or 'early adopter' is more precise in technical contexts." },
  { regex: new RegExp("(?:bring(?:ing|s)?|brought)\\s+home\\s+the\\s+bacon", "gi"), phrase: "bring home the bacon", alternatives: ["bring home the results","earn a living","win the prize"], reason: "Describes slaughtered pig flesh as the fruit of success. 'Bring home the results' or 'earn a living' carries the same meaning." },
  { regex: new RegExp("tak(e|ing|es|en)\\s+the\\s+bull\\s+by\\s+the\\s+horns|took\\s+the\\s+bull\\s+by\\s+the\\s+horns", "gi"), phrase: "take the bull by the horns", alternatives: ["tackle the problem directly","face it head-on","confront the issue"], reason: "Bullfighting/rodeo imagery. 'Tackle the problem directly' or 'face it head-on' is cleaner." },
  { regex: new RegExp("(like\\s+(a\\s+)?)?lambs?\\s+to\\s+the\\s+slaughter", "gi"), phrase: "lambs to the slaughter", alternatives: ["without resistance","unknowingly walking into danger","defenseless"], reason: "Direct slaughter imagery. 'Without resistance' or 'unknowingly walking into danger' captures the same meaning." },
  { regex: new RegExp("(no|not\\s+enough)\\s+room\\s+to\\s+swing\\s+a\\s+cat", "gi"), phrase: "no room to swing a cat", alternatives: ["extremely tight space","very cramped"], reason: "Violent animal imagery for 'cramped.' 'Extremely tight space' says it directly." },
  { regex: new RegExp("\\bred\\s+herring\\b", "gi"), phrase: "red herring", alternatives: ["distraction","false lead","misleading clue"], reason: "Originates from dead, smoked fish reportedly used to train hunting dogs. 'Distraction' or 'false lead' communicates the idea directly." },
  { regex: new RegExp("curiosity\\s+killed\\s+the\\s+cat", "gi"), phrase: "curiosity killed the cat", alternatives: ["curiosity backfired","being nosy caused trouble","curiosity led to trouble"], reason: "A direct reference to killing a cat, used as a cautionary phrase. 'Curiosity backfired' or 'being nosy caused trouble' says the same thing." },
  { regex: new RegExp("(running\\s+around\\s+)?like\\s+a\\s+chicken\\s+with\\s+(its|their)\\s+head\\s+cut\\s+off", "gi"), phrase: "like a chicken with its head cut off", alternatives: ["like your hair is on fire","in a panic","frantic and aimless"], reason: "Graphic slaughter imagery used to describe panic. 'In a panic' or 'like your hair is on fire' captures the same thing." },
  { regex: new RegExp("(your|their|his|her|my|our)\\s+goose\\s+is\\s+cooked", "gi"), phrase: "your goose is cooked", alternatives: ["you're in trouble","you're done for","you're dead in the water"], reason: "Killing-and-cooking imagery used to mean someone is in trouble. 'You're in trouble' says it directly." },
  { regex: new RegExp("thr(ow|owing|own|ew)(\\s+(someone|them|him|her|us|me))?\\s+to\\s+the\\s+wolves", "gi"), phrase: "throw someone to the wolves", alternatives: ["abandon to criticism","sacrifice someone","leave exposed"], reason: "Frames a person as prey. 'Abandon to criticism' or 'leave exposed' carries the same meaning without the imagery." },
  { regex: new RegExp("hook,?\\s+line,?\\s+and\\s+sinker", "gi"), phrase: "hook, line, and sinker", alternatives: ["completely","without question","fell for it entirely"], reason: "References the equipment used to hook and kill fish. 'Completely' or 'without question' conveys total buy-in without the fishing imagery." },
  { regex: new RegExp("clip(s|ped|ping)?\\s+(someone's|their|his|her)?\\s*wings", "gi"), phrase: "clip someone's wings", alternatives: ["restrict freedom","limit options","hold back"], reason: "Wing-clipping is a real physical mutilation done to captive birds. 'Restrict freedom' or 'limit options' says the same thing directly." },
  { regex: new RegExp("straw\\s+that\\s+broke\\s+the\\s+camel'?s\\s+back|last\\s+straw", "gi"), phrase: "straw that broke the camel's back", alternatives: ["tipping point","breaking point","final blow"], reason: "Overloading a pack animal until its back breaks. 'Tipping point' or 'breaking point' carries the same meaning." },
  { regex: new RegExp("(a\\s+)?bird\\s+in\\s+the\\s+hand(\\s+is\\s+worth)?", "gi"), phrase: "a bird in the hand", alternatives: ["a sure thing beats a possibility","a guaranteed outcome is worth more"], reason: "References trapping wild birds. 'A sure thing beats a possibility' carries the same meaning." },
  { regex: new RegExp("\\beat(ing)?\\s+crow\\b", "gi"), phrase: "eat crow", alternatives: ["admit being wrong","swallow one's pride","accept humiliation"], reason: "References eating a killed bird as humiliating punishment. 'Admit being wrong' or 'swallow one's pride' says the same thing directly." },
  { regex: new RegExp("f(ight|ights|ighting|ought)\\s+like\\s+cats\\s+and\\s+dogs", "gi"), phrase: "fight like cats and dogs", alternatives: ["constantly argue","clash frequently"], reason: "Animal-fighting imagery. 'Constantly argue' or 'clash frequently' says it directly." },
  { regex: new RegExp("(?:take|taking|took)\\s+the\\s+bait", "gi"), phrase: "take the bait", alternatives: ["fall for it","be lured in","be deceived"], reason: "References baiting hooks and traps to catch and kill animals. 'Fall for it' or 'be deceived' is more direct." },
  { regex: new RegExp("(don'?t\\s+)?count(ing)?\\s+your\\s+chickens(\\s+before)?", "gi"), phrase: "don't count your chickens", alternatives: ["don't assume success prematurely","don't celebrate too early"], reason: "Commodity framing of chickens as a yield to be counted. 'Don't assume success prematurely' says it directly." },
  { regex: new RegExp("\\blivestock\\b", "gi"), phrase: "livestock", alternatives: ["farmed animals"], reason: "Commodity framing that groups sentient beings as 'stock.' 'Farmed animals' keeps the meaning without the commodity framing." },
  { regex: new RegExp("\\bpoultry\\b", "gi"), phrase: "poultry", alternatives: ["farmed birds","chickens and turkeys"], reason: "Commodity framing for farmed birds. 'Farmed birds' or the specific species keeps the meaning without the commodity framing." },
  { regex: new RegExp("gestation\\s+(crate|stall)s?", "gi"), phrase: "gestation crate", alternatives: ["pregnancy cage"], reason: "Industry euphemism for a metal enclosure so small a pregnant sow cannot turn around for her entire 3.5-month pregnancy. 'Pregnancy cage' is accurate." },
  { regex: new RegExp("\\bdepopulat(ion|ed|ing)\\b", "gi"), phrase: "depopulation", alternatives: ["mass killing","killed en masse"], reason: "Industry euphemism for killing entire flocks or herds at once. 'Mass killing' is the accurate term. (Suppressed in database or population-statistics contexts where the word refers to removing records.)" },
  { regex: new RegExp("(meat[\\s-]?packing|meat|packing|processing)\\s+(plant|facility)s?", "gi"), phrase: "meat plant", alternatives: ["slaughterhouse"], reason: "Industry euphemisms for slaughterhouse. 'Slaughterhouse' is the accurate term. (Suppressed in clearly non-animal contexts like data or chemical processing.)" },
  { regex: new RegExp("farrowing\\s+(crate|stall)s?", "gi"), phrase: "farrowing crate", alternatives: ["birthing cage"], reason: "Industry euphemism for the metal cage confining a sow during birth and nursing. 'Birthing cage' is accurate." },
  { regex: new RegExp("battery[\\s-]cage[ds]?", "gi"), phrase: "battery cage", alternatives: ["small wire cage","confined cage"], reason: "Industry euphemism for wire enclosures that give each hen less floor space than a sheet of paper. 'Small wire cage' describes what it is." },
  { regex: new RegExp("spent\\s+hens?", "gi"), phrase: "spent hen", alternatives: ["hen killed after egg production declines"], reason: "'Spent' frames the hen as a depleted resource. Naming what actually happens — she is killed when her egg production falls — is more accurate." },
  { regex: new RegExp("humane(ly)?\\s+(slaughter(ed)?|killing|death)", "gi"), phrase: "humane slaughter", alternatives: ["slaughter","killing"], reason: "Industry oxymoron — a killing cannot be 'humane' to the one being killed. Drop the modifier and use 'slaughter' or 'killing.'" },
  { regex: new RegExp("\\bbroiler\\s+(chickens?|hens?)|broilers\\b", "gi"), phrase: "broiler chicken", alternatives: ["chicken raised for meat"], reason: "Industry term that defines a chicken by its commercial purpose. 'Chicken raised for meat' is the human-readable version. (The kitchen appliance is not flagged.)" },
  { regex: new RegExp("don'?t\\s+be\\s+a\\s+chicken", "gi"), phrase: "don't be a chicken", alternatives: ["don't hesitate","be brave","go for it"], reason: "Uses a chicken as an insult for cowardice. 'Don't hesitate' or 'be brave' is direct and doesn't rely on a demeaning stereotype." },
  { regex: new RegExp("\\bbadger(ed|ing|s)?\\b", "gi"), phrase: "badger someone", alternatives: ["pester","pressure","harass"], reason: "Comes from badger-baiting, a blood sport where dogs were set on captive badgers. 'Pester' or 'pressure' carries the same meaning without the origin." },
  { regex: new RegExp("\\bferret(ed|ing)?\\s+out\\b", "gi"), phrase: "ferret out", alternatives: ["uncover","discover","dig up"], reason: "Refers to the historical use of ferrets to flush rabbits out of burrows to be killed. 'Uncover' or 'dig up' works just as well." },
  { regex: new RegExp("cattle[,]?\\s+(not|vs\\.?|versus)\\s+pets|pets\\s+not\\s+cattle", "gi"), phrase: "cattle not pets", alternatives: ["ephemeral vs. persistent","disposable vs. unique","numbered vs. named"], reason: "Infrastructure metaphor that Google's own style guide flags for removal as 'figurative language that relates to the slaughter of animals.' 'Ephemeral vs. persistent' or 'disposable vs. unique' captures the same architectural concept." },
  { regex: new RegExp("canary\\s+in\\s+(a|the)\\s+coal\\s+mine", "gi"), phrase: "canary in a coal mine", alternatives: ["early warning signal","leading indicator","sentinel"], reason: "Refers to canaries historically placed in coal mines to die first as a warning to miners. 'Early warning signal' or 'sentinel' conveys the meaning without the harm." },
  { regex: new RegExp("fishing\\s+expeditions?", "gi"), phrase: "fishing expedition", alternatives: ["exploratory investigation","speculative inquiry","unfocused search"], reason: "Frames speculative inquiry as fishing — the metaphor softens the catch. 'Exploratory investigation' is clearer, especially in legal writing." },
  { regex: new RegExp("\\bsacred\\s+cows?\\b", "gi"), phrase: "sacred cow", alternatives: ["unquestioned belief","untouchable topic","protected assumption"], reason: "Treats cattle as objects in an 'untouchable' metaphor while also trivializing Hindu beliefs. 'Unquestioned belief' or 'protected assumption' avoids both issues." },
  { regex: new RegExp("\\bscapegoat(ed|ing|s)?\\b", "gi"), phrase: "scapegoat", alternatives: ["blame target","fall person","wrongly blamed"], reason: "Originates from the ritual sacrifice of goats to carry away blame. 'Blame target' or 'wrongly blamed' is more precise." },
  { regex: new RegExp("dead[\\s_-]?cat[\\s_-]?bounce", "gi"), phrase: "dead cat bounce", alternatives: ["temporary rebound","false recovery","brief uptick"], reason: "A financial term built on the image of a dead cat. 'Temporary rebound' or 'false recovery' is more professional and avoids the image." },
  { regex: new RegExp("\\bdog[\\s-]eat[\\s-]dog\\b", "gi"), phrase: "dog-eat-dog", alternatives: ["ruthlessly competitive","cutthroat","fiercely competitive"], reason: "Frames dogs as inherently violent toward each other as a model for competition. 'Ruthlessly competitive' or 'cutthroat' conveys the meaning without the stereotype." },
  { regex: new RegExp("\\bwhack[\\s-]a[\\s-]mole\\b", "gi"), phrase: "whack-a-mole", alternatives: ["recurring problem","endless loop","unwinnable game"], reason: "References a game built around repeatedly striking animals as they pop up. 'Recurring problem' or 'endless loop' describes the pattern more precisely." },
  { regex: new RegExp("cash\\s+cows?", "gi"), phrase: "cash cow", alternatives: ["moneymaker","profit center","reliable revenue source"], reason: "Treats a cow as a thing to be extracted from for profit. 'Moneymaker' or 'profit center' carries the same meaning." },
  { regex: new RegExp("\\bsacrificial\\s+lambs?\\b", "gi"), phrase: "sacrificial lamb", alternatives: ["expendable person","person set up to fail","someone sacrificed for others"], reason: "References the ritual slaughter of lambs. 'Expendable person' or 'someone sacrificed for others' communicates the metaphor directly." },
  { regex: new RegExp("\\bsitting\\s+ducks?\\b", "gi"), phrase: "sitting duck", alternatives: ["easy target","vulnerable target","exposed"], reason: "Hunting imagery — a duck in the open, easy to shoot. 'Easy target' or 'vulnerable target' says the same thing." },
  { regex: new RegExp("\\bopen\\s+season\\b", "gi"), phrase: "open season", alternatives: ["free-for-all","unrestricted criticism","no holds barred"], reason: "Refers to the legal hunting period when killing animals is permitted. 'Free-for-all' or 'no holds barred' conveys the meaning without the hunting framing." },
  { regex: new RegExp("put(s|ting)?(\\s+(him|her|them))?\\s+out\\s+to\\s+pasture", "gi"), phrase: "put out to pasture", alternatives: ["retire","phase out","sunset"], reason: "Refers to the farm practice of disposing of animals once they're no longer productive. 'Retire,' 'phase out,' or 'sunset' is clearer and carries no harm." },
  { regex: new RegExp("\\bdead\\s+ducks?\\b", "gi"), phrase: "dead duck", alternatives: ["lost cause","doomed effort","foregone conclusion"], reason: "Hunting imagery — a duck that has been shot and killed. 'Lost cause' or 'doomed effort' is just as expressive." },
  { regex: new RegExp("\\bcull(ed|ing|s)?\\b", "gi"), phrase: "cull", alternatives: ["remove","prune","trim","filter out"], reason: "Euphemism used in wildlife management and farming for mass killing. 'Remove', 'prune', 'trim', or 'filter out' is accurate in technical contexts." },
  { regex: new RegExp("\\bveal(\\s+cal(f|ves))?\\b", "gi"), phrase: "veal", alternatives: ["calf flesh","calf meat"], reason: "'Veal' softens 'slaughtered-calf flesh' via a Norman-French borrowing. In advocacy or industry-critical writing, 'calf flesh' names what it is. (Suppressed in recipes and cooking contexts.)" },
  { regex: new RegExp("\\blame[\\s-]duck\\b", "gi"), phrase: "lame duck", alternatives: ["outgoing","transitional","ineffective"], reason: "Combines an ableist adjective with a reference to a bird unable to fly due to injury. 'Outgoing', 'transitional', or 'ineffective' is more precise." },
  { regex: new RegExp("\\bdebeak(ing|ed)|beak\\s+(trimming|trim|conditioning)\\b", "gi"), phrase: "debeaking", alternatives: ["beak amputation","beak mutilation"], reason: "Industry euphemism for slicing or burning off hens' beaks, typically without anesthesia. 'Beak amputation' names what actually happens." },
  { regex: new RegExp("\\bdehorn(ing|ed)|disbud(ding|ded)\\b", "gi"), phrase: "dehorning", alternatives: ["horn amputation","horn removal"], reason: "Industry term for removing cattle horns, typically without anesthesia. 'Horn amputation' is accurate." },
  { regex: new RegExp("tail[\\s-]docking|tail\\s+docked|docked\\s+tail", "gi"), phrase: "tail docking", alternatives: ["tail amputation"], reason: "Amputating pigs', sheep's, or dogs' tails. 'Tail amputation' is the accurate term." },
  { regex: new RegExp("ear[\\s-]notch(ing|ed)", "gi"), phrase: "ear notching", alternatives: ["ear mutilation"], reason: "Industry identification practice of cutting notches in animals' ears. 'Ear mutilation' names what it is." },
  { regex: new RegExp("ventilation\\s+shutdown(\\s+plus)?|VSD\\+|VSD\\s+plus", "gi"), phrase: "ventilation shutdown", alternatives: ["mass killing by suffocation","heat-and-suffocation killing"], reason: "Industry term for killing entire flocks by cutting off airflow — the animals die from suffocation and heat. 'Mass killing by suffocation' is the accurate term. (Suppressed in HVAC contexts.)" },
  { regex: new RegExp("(maceration\\s+of\\s+chicks|chick\\s+maceration|macerat(ed|ing)\\s+chicks)", "gi"), phrase: "maceration of chicks", alternatives: ["grinding newborn chicks alive","chick grinding"], reason: "Industry euphemism for killing day-old male chicks by grinding them alive. Say what the process is. (Bare 'maceration' in culinary or chemistry contexts is not flagged.)" },
  { regex: new RegExp("\\babattoirs?\\b", "gi"), phrase: "abattoir", alternatives: ["slaughterhouse"], reason: "French-derived euphemism for slaughterhouse. 'Slaughterhouse' is the accurate English term." },
  { regex: new RegExp("rendering\\s+(plant|facility)s?", "gi"), phrase: "rendering plant", alternatives: ["animal-body processing plant","carcass-processing facility"], reason: "Facility that processes animal bodies — roadkill, downed animals, slaughter byproducts — into meal, fat, and tallow. Naming it accurately makes the supply chain visible. (Only the full compound 'rendering plant' / 'rendering facility' is flagged; bare 'rendering' for graphics or UI is not.)" },
  { regex: new RegExp("\\bstockyards?\\b", "gi"), phrase: "stockyard", alternatives: ["slaughterhouse pens","live-animal market"], reason: "Euphemism for pre-slaughter holding pens. 'Slaughterhouse pens' describes what the facility actually is." },
  { regex: new RegExp("(laying|layer)\\s+hens?", "gi"), phrase: "laying hen", alternatives: ["hen"], reason: "Defines a hen by her egg-laying function. When sex and species are relevant, 'hen' is sufficient." },
  { regex: new RegExp("(dairy|beef)\\s+(cow|cows|cattle)|meat\\s+(birds?|rabbits?|goats?)", "gi"), phrase: "dairy cow", alternatives: ["cow","the species name alone"], reason: "Defines an animal by the product humans extract from them. The species name alone is sufficient unless the use is actively relevant." },
  { regex: new RegExp("brood\\s+sows?|breeding\\s+(stock|pair)", "gi"), phrase: "brood sow", alternatives: ["pregnant pig","nursing mother pig"], reason: "Defines a female animal by her reproductive function. Name the individual directly where possible." },
  { regex: new RegExp("cattle\\s+calls?", "gi"), phrase: "cattle call", alternatives: ["open call","mass audition"], reason: "Likens human applicants to livestock being herded. 'Open call' or 'mass audition' carries the same meaning without the framing." },
  { regex: new RegExp("pet\\s+projects?", "gi"), phrase: "pet project", alternatives: ["side project","passion project"], reason: "Carries over the property framing of 'pet' (something owned) to the project. 'Side project' or 'passion project' captures the same idea without the ownership framing." },
  { regex: new RegExp("humanely\\s+(raised|produced|farmed)", "gi"), phrase: "humanely raised", alternatives: ["factory-farmed","raised in [specific conditions]"], reason: "USDA-unregulated marketing label — companies define their own standards, and the actual conditions often differ little from factory farming. Describe the actual conditions where possible." },
  { regex: new RegExp("free[\\s-]rang(e|ing)|free[\\s-]roaming", "gi"), phrase: "free-range", alternatives: ["minimally accessible outdoor pen","outdoor access (USDA minimum)"], reason: "USDA requires only 'access to outdoors' — often a small door to a small porch that most birds never use. The label does not guarantee meaningful outdoor life." },
  { regex: new RegExp("pasture[\\s-]raised|pastured", "gi"), phrase: "pasture-raised", alternatives: ["raised on pasture (certifier-dependent)"], reason: "Not USDA-regulated; the meaning depends on whichever certifier the producer chooses. Name the certifier and the actual conditions where possible." },
  { regex: new RegExp("grass[\\s-](fed|finished)", "gi"), phrase: "grass-fed", alternatives: ["grass-fed (USDA definition dropped 2016)","forage-finished"], reason: "Describes the cattle's feed, not their welfare. Slaughter, transport, and mother-calf separation happen the same way. The USDA dropped its 'grass-fed' definition in 2016; current usage is producer-defined." },
  { regex: new RegExp("cage[\\s-]free\\s+(chicken|turkey|meat|pork|beef)", "gi"), phrase: "cage-free chicken", alternatives: ["crowded indoor housing","barn-raised"], reason: "Meaningless for meat birds — broiler chickens and turkeys are almost never caged in industrial production. The label implies a welfare improvement that doesn't exist. (Cage-free for eggs IS a meaningful distinction; that usage is not flagged.)" },
  { regex: new RegExp("Certified\\s+Humane|Animal\\s+Welfare\\s+Approved|Global\\s+Animal\\s+Partnership|American\\s+Humane\\s+Certified|One\\s+Health\\s+Certified|GAP\\s+(certified|Step(\\s+\\d)?)", "gi"), phrase: "Certified Humane", alternatives: ["name the certifier and standard"], reason: "Third-party welfare certifications with widely varying standards — some are meaningful (Animal Welfare Approved), others are marketing (American Humane Certified). Name the specific standard if relevant." },
  { regex: new RegExp("(ethically|responsibly)\\s+sourced\\s+(meat|dairy|eggs|beef|pork|chicken)|happy\\s+(meat|cows?)", "gi"), phrase: "ethically sourced meat", alternatives: ["describe the actual farm practices"], reason: "Marketing language without a standard definition when applied to animal products. 'Ethically sourced' meat has no USDA definition. Describe the actual practices instead. (The phrase applied to coffee, chocolate, or textiles is not flagged.)" },
  { regex: new RegExp("dolphin[\\s-]safe|line[\\s-]caught|pole[\\s-](and[\\s-]line[\\s-])?caught|sustainab(ly\\s+caught|le\\s+seafood)", "gi"), phrase: "dolphin-safe", alternatives: ["name the specific fishing method and bycatch statistics"], reason: "Addresses specific bycatch concerns but not fish suffering. Fish feel pain, suffocate on deck, or are crushed in nets regardless of how the boat avoids catching dolphins or catches fish one at a time." },
  { regex: new RegExp("(feed|fed|feeding)\\s+to\\s+the\\s+(lions|sharks|dogs)", "gi"), phrase: "feed to the lions", alternatives: ["sacrifice","leave exposed","abandon to attack"], reason: "Human-as-prey imagery. 'Sacrifice' or 'leave exposed' captures the same meaning." },
  { regex: new RegExp("(like\\s+(a\\s+)?)?pigs?\\s+to\\s+slaughter", "gi"), phrase: "like a pig to slaughter", alternatives: ["defenseless","walking into disaster"], reason: "Direct slaughter imagery. 'Defenseless' or 'walking into disaster' captures the same meaning." },
  { regex: new RegExp("turkey[\\s-]shoot", "gi"), phrase: "turkey shoot", alternatives: ["trivially easy win","no-contest situation","walkover"], reason: "One-sided-slaughter imagery for an easy win. 'Walkover' or 'trivially easy win' carries the same meaning." },
  { regex: new RegExp("fox(es)?\\s+(guarding\\s+the|in\\s+the)\\s+hen[\\s-]?house", "gi"), phrase: "fox guarding the henhouse", alternatives: ["conflict of interest","the wrong person in charge"], reason: "Frames predation as an inevitable natural order. 'Conflict of interest' or 'wrong person in charge' is the actual point being made." },
  { regex: new RegExp("(like\\s+a\\s+)?bull\\s+in\\s+a\\s+china\\s+shop", "gi"), phrase: "bull in a china shop", alternatives: ["tornado in a glass factory","clumsy disruption","careless and destructive"], reason: "Bull-as-clumsy-brute stereotype — actually originates from a cartoon, not reality. 'Clumsy disruption' or 'careless and destructive' is more accurate." },
  { regex: new RegExp("build(s|ing)?\\s+a\\s+better\\s+mousetrap|better\\s+mousetrap", "gi"), phrase: "build a better mousetrap", alternatives: ["build a better mouse pad","invent something better"], reason: "Mouse-killing device as innovation metaphor. 'Invent something better' or 'build a better mouse pad' captures the idea." },
  { regex: new RegExp("(packed|squeezed)\\s+(in\\s+)?like\\s+sardines", "gi"), phrase: "packed in like sardines", alternatives: ["packed in like pickles","tightly crowded","crammed together"], reason: "Accurately describes industrial fishing and canning — the 'imagery' is the reality. 'Tightly crowded' or 'packed in like pickles' works without invoking it." },
  { regex: new RegExp("pull(s|ing|ed)?\\s+the\\s+wool\\s+over", "gi"), phrase: "pull the wool over", alternatives: ["deceive","mislead","pull the polyester over your eyes"], reason: "Wool (sheep exploitation) as a deception metaphor. 'Deceive' or 'mislead' is direct and clearer." },
  { regex: new RegExp("(put(s|ting)?\\s+)?lipstick\\s+on\\s+a\\s+pig", "gi"), phrase: "lipstick on a pig", alternatives: ["superficially improve","disguise the flaw","dress up a bad product"], reason: "Frames pigs as ugly objects. 'Superficially improve' or 'disguise the flaw' is the actual meaning." },
  { regex: new RegExp("silk\\s+purse\\s+(out\\s+of|from)\\s+a\\s+sow's\\s+ear", "gi"), phrase: "silk purse out of a sow's ear", alternatives: ["diamond bracelet out of a lump of coal","transform something unpromising"], reason: "Pig body parts framed as worthless. 'Transform something unpromising' carries the same meaning." },
  { regex: new RegExp("black\\s+sheep", "gi"), phrase: "black sheep", alternatives: ["outlier","misfit","odd one out"], reason: "Commodifies sheep coat color as a family-shame metaphor, with racial baggage. 'Outlier' or 'odd one out' works." },
  { regex: new RegExp("wol(f|ves)\\s+in\\s+sheep'?s\\s+clothing", "gi"), phrase: "wolf in sheep's clothing", alternatives: ["deceiver in disguise","hidden threat","threat wearing a friendly face"], reason: "Wolves-as-deceivers trope. 'Hidden threat' or 'deceiver in disguise' carries the same meaning." },
  { regex: new RegExp("chicken(s|ed|ing)\\s+out|chicken\\s+out", "gi"), phrase: "chicken out", alternatives: ["back out","lose nerve","get cold feet"], reason: "Chicken-as-coward framing. 'Back out' or 'lose nerve' carries the same meaning." },
  { regex: new RegExp("feeding\\s+frenz(y|ies)", "gi"), phrase: "feeding frenzy", alternatives: ["chaotic rush","scramble to exploit","uncontrolled grab"], reason: "Shark-predation imagery used for human behavior. 'Chaotic rush' or 'scramble to exploit' carries the same meaning." },
  { regex: new RegExp("(smell[s]?\\s+)?blood\\s+in\\s+the\\s+water", "gi"), phrase: "blood in the water", alternatives: ["signs of weakness","vulnerability visible","sensing a kill"], reason: "Shark-predation imagery. 'Signs of weakness' or 'vulnerability visible' carries the same meaning." },
  { regex: new RegExp("(circl(e|ing)\\s+(like\\s+)?vultures|vultures\\s+circling)", "gi"), phrase: "circling like vultures", alternatives: ["waiting to exploit","hovering opportunistically","waiting for weakness"], reason: "Species defamation — the 'circling vulture' framing is factually wrong (vultures are ecological cleaners, not predators) and has driven real persecution; vulture populations are crashing globally. 'Waiting to exploit' carries the same meaning." },
  { regex: new RegExp("mad(der)?\\s+(than|as)\\s+a\\s+wet\\s+hen", "gi"), phrase: "madder than a wet hen", alternatives: ["furious","livid","seething"], reason: "References the farm practice of dunking broody hens in water to break their nesting instinct. 'Furious' or 'livid' says it directly." },
  { regex: new RegExp("code\\s+monkeys?", "gi"), phrase: "code monkey", alternatives: ["developer","programmer","engineer"], reason: "Frames programmers as trained animals, and compounds with the long history of 'monkey' used as a racial slur. 'Developer' or 'engineer' is the accurate term." },
  { regex: new RegExp("(memory|CPU|bandwidth|resource|disk|space)\\s+hog|hogging\\s+(memory|CPU|bandwidth|resources|the)|hogs\\s+the|hog\\s+the\\s+spotlight", "gi"), phrase: "memory hog", alternatives: ["resource-intensive","heavy consumer","monopolizes","dominates"], reason: "Builds on the pig-as-greedy stereotype (pigs are actually selective eaters). 'Resource-intensive' or 'monopolizes' is more accurate and avoids the framing." },
  { regex: new RegExp("\\bpig[\\s-]?headed(ness)?\\b", "gi"), phrase: "pigheaded", alternatives: ["obstinate","inflexible","unreasonable"], reason: "Pig-as-stubborn stereotype (pigs are intelligent, not stubborn). 'Obstinate' or 'unreasonable' says it directly." },
  { regex: new RegExp("eat(s|ing|e)?\\s+like\\s+a\\s+pig|ate\\s+like\\s+a\\s+pig|pig(s|ged|ging)?\\s+out", "gi"), phrase: "eat like a pig", alternatives: ["overeat","gorge","eat voraciously"], reason: "Pig-as-glutton stereotype (actually wrong — pigs are selective eaters in natural conditions). 'Overeat' or 'gorge' says the same thing." },
  { regex: new RegExp("sons?[\\s-]of[\\s-]a[\\s-]bitch|sons\\s+of\\s+bitches", "gi"), phrase: "son of a bitch", alternatives: ["specific descriptor"], reason: "Female-dog insult that compounds misogyny with species defamation. A specific descriptor is clearer and doesn't land on anyone's mother or on dogs." },
  { regex: new RegExp("\\bsheeple\\b", "gi"), phrase: "sheeple", alternatives: ["conformists","unquestioning followers","uncritical crowd"], reason: "Coined term meaning 'sheep-people' — dehumanizes the target while defaming sheep (who are actually complex social animals). 'Conformists' or 'uncritical crowd' carries the same meaning." },
  { regex: new RegExp("(loan|card)[\\s-]sharks?", "gi"), phrase: "loan shark", alternatives: ["predatory lender","hustler","card hustler"], reason: "Species-as-predator trope applied to exploitative humans, which misrepresents sharks and provides a convenient framing for financial harm. 'Predatory lender' or 'hustler' is direct and more accurate." },
  { regex: new RegExp("vulture\\s+(capitalist|capitalism|fund)s?", "gi"), phrase: "vulture capitalist", alternatives: ["predatory investor","scavenger capitalist","distressed-debt investor"], reason: "Species defamation that drives real-world vulture persecution — global vulture populations are crashing largely from this kind of cultural framing. 'Predatory investor' names the behavior without defaming an ecologically critical species." },
  { regex: new RegExp("weasel\\s+words?|weasel(s|ed|ing)?\\s+out", "gi"), phrase: "weasel words", alternatives: ["evasive language","evade","slippery phrasing"], reason: "Species-as-deceitful trope. 'Evasive language' or 'slippery phrasing' is more direct. (Wikipedia's Manual of Style uses 'weasel words' as an internal term of art; that context is suppressed.)" },
  { regex: new RegExp("leech(es|ed|ing)?\\s+off|bloodsuckers?", "gi"), phrase: "leech off", alternatives: ["freeload","mooch","exploit","parasitic"], reason: "Species-as-parasite trope. 'Freeload' or 'mooch' is direct. (Bare 'leech' in medical contexts — leeches are still used in some surgeries — is not flagged.)" },
  { regex: new RegExp("monkey\\s+business|monkey(s|ing|ed)?\\s+around|(make|makes|making|made)\\s+a\\s+monkey\\s+of", "gi"), phrase: "monkey business", alternatives: ["mischief","fool around","tamper with","make a fool of"], reason: "Primate-as-foolish stereotype with a long racial history. 'Mischief' or 'fool around' is direct and doesn't carry the baggage." },
  { regex: new RegExp("not\\s+my\\s+(circus[,]?\\s+not\\s+my\\s+monkeys?|monkeys?|circus)", "gi"), phrase: "not my circus, not my monkeys", alternatives: ["not my problem","not my concern","not my mess to clean up"], reason: "Direct reference to circus-animal exploitation. 'Not my problem' carries the same meaning." },
  { regex: new RegExp("\\bbird[\\s-]?brain(ed)?\\b", "gi"), phrase: "bird brain", alternatives: ["forgetful","absent-minded","scatter-brained"], reason: "Bird-as-stupid stereotype (corvids and parrots rank among the most cognitively sophisticated non-human animals). 'Forgetful' or 'absent-minded' is more accurate." },
  { regex: new RegExp("foie[\\s-]gras", "gi"), phrase: "foie gras", alternatives: ["force-fed duck liver","force-fed goose liver"], reason: "French for 'fat liver'; obscures that the product comes from force-feeding ducks or geese until their livers enlarge to ten times normal size. Name the process." },
  { regex: new RegExp("\\bchevon\\b", "gi"), phrase: "chevon", alternatives: ["goat flesh","goat meat"], reason: "Marketing-constructed word (coined in the 1920s) to make goat meat palatable to Anglophone consumers. 'Goat flesh' or 'goat meat' is accurate." },
  { regex: new RegExp("\\bsweetbreads?\\b", "gi"), phrase: "sweetbread", alternatives: ["calf thymus","calf pancreas","lamb thymus"], reason: "Opaque culinary term for calf or lamb thymus or pancreas. Naming the organ is clearer. (Suppressed in recipe/cooking contexts.)" },
  { regex: new RegExp("\\bmutton\\b", "gi"), phrase: "mutton", alternatives: ["sheep flesh","sheep meat"], reason: "'Mutton' obscures the species. 'Sheep flesh' names it. (Suppressed in recipe contexts.)" },
  { regex: new RegExp("\\bvenison\\b", "gi"), phrase: "venison", alternatives: ["deer flesh","deer meat"], reason: "'Venison' obscures the species. 'Deer flesh' names it. (Suppressed in recipe or hunting-regulation contexts.)" },
  { regex: new RegExp("\\bsquabs?\\b", "gi"), phrase: "squab", alternatives: ["pigeon flesh","young pigeon meat"], reason: "Marketing term for young pigeon raised for slaughter. 'Pigeon flesh' names what it is. (Suppressed in recipe contexts.)" },
  { regex: new RegExp("\\bspare[\\s-]?ribs\\b", "gi"), phrase: "spare ribs", alternatives: ["pig ribs"], reason: "'Spare' frames body parts as disposable/extra. 'Pig ribs' is accurate. (Suppressed in recipe/BBQ contexts.)" },
  { regex: new RegExp("\\b(genuine|real|top[\\s-]grain|full[\\s-]grain)?\\s*leather\\b", "gi"), phrase: "leather", alternatives: ["cow skin","animal skin","vegan leather","synthetic leather","plant leather"], reason: "'Leather' obscures that the material is the skin of a killed cow (or pig, sheep, etc.). In advocacy or supply-chain writing, naming it is clearer. Suppressed in fashion/product contexts where the industry term is expected." },
  { regex: new RegExp("\\b(merino\\s+|lambs)?wool\\b", "gi"), phrase: "wool", alternatives: ["sheep hair","synthetic fiber","plant fiber"], reason: "'Wool' obscures that the fiber is sheep hair, usually from sheep bred for extreme coat yields (mulesing, shearing injury, eventual slaughter). Advocacy writing names it directly. Suppressed in textile/fashion contexts." },
  { regex: new RegExp("down\\s+(feathers|jacket|comforter|pillow|filling)|(goose|duck)\\s+down", "gi"), phrase: "down feathers", alternatives: ["plant-based insulation","synthetic fill","recycled fill"], reason: "Down is plucked from ducks and geese, often while alive and distressed. 'Plant-based insulation' or 'synthetic fill' describes the alternative. Bare 'down' (direction) is NOT flagged — only product compounds." },
  { regex: new RegExp("\\bcashmere|mohair|angora\\b", "gi"), phrase: "cashmere", alternatives: ["goat hair","rabbit hair","recycled fiber","synthetic alternative"], reason: "Luxury-marketing names that obscure the animal source. Cashmere and mohair come from goats; angora comes from rabbits (who are often plucked live and injured). Naming the species is clearer in advocacy writing." },
  { regex: new RegExp("\\b(pure\\s+|mulberry\\s+|raw\\s+)?silk\\b", "gi"), phrase: "silk", alternatives: ["plant silk","peace silk","synthetic silk","recycled fiber"], reason: "Silk production typically requires boiling silkworms alive inside their cocoons to prevent the thread from breaking. Peace silk, plant silk, and synthetics avoid this. Suppressed in textile/fashion contexts." },
  { regex: new RegExp("royal\\s+jelly|beeswax|propolis", "gi"), phrase: "royal jelly", alternatives: ["plant alternative","candelilla wax","carnauba wax","soy wax"], reason: "Bee products are extracted through industrial beekeeping, which involves queen-clipping, smoke stressing, and often the destruction of hives. Plant-based waxes (candelilla, carnauba, soy) serve most of the same purposes." },
  { regex: new RegExp("down(ed|er)\\s+(animal|cow|cattle|pig)s?", "gi"), phrase: "downed animal", alternatives: ["animal too sick or injured to walk","collapsed animal"], reason: "'Downed' uses passive voice to elide why the animal is on the ground — untreated injury or illness in transport or on the farm. 'Too sick to walk' names the condition." },
  { regex: new RegExp("(artificial|forced)\\s+insemination|AI\\s+in\\s+(cattle|cows|dairy|pigs|sheep|swine)", "gi"), phrase: "artificial insemination", alternatives: ["forced impregnation"], reason: "Industry-standard procedure involving restraint and reproductive invasion. 'Forced impregnation' is the accurate term when the animal cannot consent. (The bare abbreviation 'AI' is not flagged — too much overlap with artificial intelligence. The rule fires only on the specific animal-ag compounds.)" },
  { regex: new RegExp("\\bfarrow(ing|ed)\\b", "gi"), phrase: "farrowing", alternatives: ["giving birth (for pigs)","piglet-birthing"], reason: "Industry verb that erases the individual animal giving birth. 'Giving birth' is the plain-language version. (The compound 'farrowing crate' is flagged by its own rule.)" },
  { regex: new RegExp("live\\s+(export(s|ing)?|transport|shipment)", "gi"), phrase: "live export", alternatives: ["transport to slaughter","export for slaughter"], reason: "Industry term for loading animals onto ships or trucks for days-to-weeks journeys to overseas slaughter. 'Transport to slaughter' names the destination." },
  { regex: new RegExp("(pork|beef|dairy|poultry|veal|egg)\\s+industry", "gi"), phrase: "pork industry", alternatives: ["pig-flesh industry","cow-flesh industry","cow-milk industry","chicken-flesh industry"], reason: "Each term names the product rather than the species it comes from. Naming the species (e.g. 'pig-flesh industry') makes the supply chain visible. Low priority — use in advocacy writing, not general documentation." },
  { regex: new RegExp("trophy\\s+(hunt(ing|er|ers)?|kill(s)?)", "gi"), phrase: "trophy hunting", alternatives: ["killing for display","recreational killing"], reason: "Frames a killed animal as an achievement to be displayed. 'Killing for display' or 'recreational killing' names the activity." },
  { regex: new RegExp("big[\\s-]game\\s+hunt(ing|er|ers)?", "gi"), phrase: "big-game hunter", alternatives: ["large-animal hunter","elephant/lion/rhino hunter"], reason: "'Big game' frames large wild animals as sport objects existing for human recreation. 'Large-animal hunter' names it; better still, name the species (elephant, lion, rhino)." },
  { regex: new RegExp("sport[\\s]?fishing|recreational\\s+fishing|game\\s+fishing", "gi"), phrase: "sport fishing", alternatives: ["recreational fishing (if literal)","recreational killing of fish"], reason: "'Sport' frames killing fish as leisure. In contexts critical of the activity, 'recreational killing of fish' is accurate. (In neutral angling-industry writing, the scanner adds noise; tune the context or disable in those files.)" },
  { regex: new RegExp("catch[\\s-]and[\\s-]release", "gi"), phrase: "catch and release", alternatives: ["capture and release","captured and released (with injury)"], reason: "Frames hook injury, exhaustion, and stress as harmless. Studies show significant post-release mortality, especially for species caught from deep water. 'Capture and release' is more neutral." },
  { regex: new RegExp("thin(s|ning|ned)?\\s+(out\\s+)?the\\s+herd", "gi"), phrase: "thin the herd", alternatives: ["reduce numbers by killing","kill off"], reason: "Culling euphemism that softens 'kill off selected animals.' 'Kill off' says it directly." },
  { regex: new RegExp("humane\\s+(traps?|removal|control)", "gi"), phrase: "humane trap", alternatives: ["non-lethal trap","non-lethal removal","live-catch trap"], reason: "'Humane' sanitizes the practice. Say whether it's lethal or non-lethal directly — 'non-lethal trap' is clearer and testable." },
  { regex: new RegExp("lethal\\s+(removal|control|management)", "gi"), phrase: "lethal removal", alternatives: ["killing program","culling program"], reason: "Bureaucratic language for killing programs. 'Killing program' says it plainly." },
  { regex: new RegExp("(fur|mink|fox)\\s+(farms?|ranch(es)?)", "gi"), phrase: "fur farm", alternatives: ["mink confinement facility","fox confinement facility","fur-industry facility"], reason: "'Farm' or 'ranch' evokes pastoral imagery; these are intensive confinement facilities where animals live in wire cages before being gassed or electrocuted. Name them directly." },
  { regex: new RegExp("fur[\\s-]bearing\\s+animals?", "gi"), phrase: "fur-bearing animal", alternatives: ["named species","fur-industry species"], reason: "Defines wild animals by a human use. Naming the species (foxes, minks, coyotes, bobcats, chinchillas) is clearer." },
  { regex: new RegExp("\\bby[\\s-]?catch\\b", "gi"), phrase: "bycatch", alternatives: ["incidental killing","non-target marine deaths"], reason: "Neutralizes the massive incidental killing of non-target marine species — hundreds of thousands of dolphins, sea turtles, seabirds, and sharks each year. 'Incidental killing' names it." },
  { regex: new RegExp("fish(ery)?\\s+stocks?", "gi"), phrase: "fish stocks", alternatives: ["fish populations","wild fish numbers"], reason: "Commodity framing of marine life as a renewable resource. 'Fish populations' is neutral and accurate." },
  { regex: new RegExp("\\baquaculture|fish\\s+farming\\b", "gi"), phrase: "aquaculture", alternatives: ["industrial fish farming","intensive fish confinement"], reason: "Neutral-sounding framing for intensive fish confinement and slaughter. In advocacy writing, 'industrial fish farming' is more accurate." },
  { regex: new RegExp("cr(y|ied|ying|ies)\\s+wolf", "gi"), phrase: "cry wolf", alternatives: ["raise false alarms","create alert fatigue","sound unjustified alerts"], reason: "Rooted in Aesop's fable, the phrase reinforces the wolf-as-menace framing that has driven centuries of wolf persecution. 'Raise false alarms' captures the meaning." },
  { regex: new RegExp("pecking\\s+orders?", "gi"), phrase: "pecking order", alternatives: ["hierarchy","chain of command","ranking"], reason: "Derived from the actual behavior of hens in confinement, where crowding causes injurious pecking. 'Hierarchy' or 'chain of command' captures the same idea." },
  { regex: new RegExp("play(s|ing|ed)?\\s+cat\\s+and\\s+mouse|(cat\\s+and\\s+mouse\\s+game|game\\s+of\\s+cat\\s+and\\s+mouse)", "gi"), phrase: "play cat and mouse", alternatives: ["drawn-out pursuit","back-and-forth chase","evasive pursuit"], reason: "Predator-prey torture metaphor — the game is about prolonging the suffering. 'Drawn-out pursuit' captures the meaning." },
  { regex: new RegExp("cat\\s+(that|who)\\s+(swallowed|ate)\\s+the\\s+canary|canary[\\s-]eating\\s+grin", "gi"), phrase: "cat that swallowed the canary", alternatives: ["smug with secret knowledge","self-satisfied grin"], reason: "Predation imagery — a dead canary is the joke's punchline. 'Smug with secret knowledge' captures it." },
  { regex: new RegExp("(chomping|champing|chomps|champs)\\s+at\\s+the\\s+bit", "gi"), phrase: "chomping at the bit", alternatives: ["eager to start","impatient to begin","raring to go"], reason: "References the metal 'bit' forced into a horse's mouth; the phrase describes the horse's attempt to relieve it. 'Eager to start' says the same thing." },
  { regex: new RegExp("whip(s|ped|ping)?\\s+into\\s+shape", "gi"), phrase: "whip into shape", alternatives: ["get organized","demand discipline","restore order"], reason: "Whip-violence imagery from animal training. 'Get organized' or 'restore order' is direct. (Political 'whip' and culinary 'whip' — different usage — are suppressed.)" },
  { regex: new RegExp("whal(e|es|ing|ed)\\s+on", "gi"), phrase: "whale on", alternatives: ["pummel","beat up","hammer"], reason: "Whaling (whale slaughter) as metaphor for repeated hitting. 'Pummel' or 'hammer' is direct." },
  { regex: new RegExp("fish\\s+or\\s+cut\\s+bait", "gi"), phrase: "fish or cut bait", alternatives: ["decide","commit or move on"], reason: "Fishing imagery. 'Decide' or 'commit or move on' is direct." },
  { regex: new RegExp("pull(s|ing|ed)?\\s+a\\s+rabbit\\s+out\\s+of\\s+a\\s+hat", "gi"), phrase: "pull a rabbit out of a hat", alternatives: ["pull a coin out of an ear","magically solve","produce unexpectedly"], reason: "Stage magic often uses live rabbits kept in distressing conditions. 'Magically solve' or 'produce unexpectedly' carries the meaning without referencing the practice." },
  { regex: new RegExp("walk(s|ing|ed)?\\s+on\\s+eggshells", "gi"), phrase: "walking on eggshells", alternatives: ["walking on thin ice","treading carefully","being extra cautious"], reason: "Commodifies eggs as fragile objects; erases the laying-hen origin. 'Walking on thin ice' carries the same meaning." },
  { regex: new RegExp("put\\s+(a|the)\\s+\\S+\\s+out\\s+of\\s+(its|their|the)\\s+misery|put\\s+(it|them)\\s+out\\s+of\\s+(its|their)\\s+misery|put\\s+out\\s+of\\s+(its|their|the)\\s+misery", "gi"), phrase: "put a horse out of its misery", alternatives: ["end the suffering","end it mercifully","conclude a painful situation"], reason: "Horse-killing idiom. 'End the suffering' carries the same meaning without the imagery." },
  { regex: new RegExp("kill(ing)?\\s+the\\s+fatted\\s+calf", "gi"), phrase: "kill the fatted calf", alternatives: ["celebrate grandly","roll out the red carpet","prepare a feast"], reason: "Biblical animal-sacrifice imagery (Luke 15 — the Prodigal Son). 'Celebrate grandly' or 'roll out the red carpet' carries the same meaning." },
  { regex: new RegExp("(acting\\s+like\\s+lemmings|lemming\\s+(investor|investors|behavior)|like\\s+lemmings)", "gi"), phrase: "acting like lemmings", alternatives: ["herd-following investor","unquestioning crowd","uncritical followers"], reason: "Based on a Disney hoax — the 1958 'White Wilderness' staged lemmings being driven off a cliff. Lemmings don't mass-suicide. The metaphor defames the species and misleads the reader." },
  { regex: new RegExp("(you|little|filthy|dirty)\\s+maggots?", "gi"), phrase: "you maggot", alternatives: ["specific descriptor"], reason: "Degrading insect insult. Most uses in documentation are quoting dialogue or user-generated content; otherwise, use a specific descriptor." },
  { regex: new RegExp("(filthy|dirty|you|capitalist|fascist|bourgeois)\\s+swine", "gi"), phrase: "filthy swine", alternatives: ["specific descriptor"], reason: "Pig-as-degraded pejorative. Naming the actual trait (greedy, exploitative, corrupt) is clearer. (Bare 'swine' in medical contexts like 'swine flu' is not flagged.)" },
  { regex: new RegExp("\\bcat[\\s-]?fights?\\b", "gi"), phrase: "cat fight", alternatives: ["heated argument","altercation","confrontation"], reason: "Gendered insult — almost exclusively applied to women arguing, framing them as cats fighting. 'Heated argument' or 'altercation' is neutral." },
  { regex: new RegExp("(humans?\\s+and\\s+animals|animals\\s+and\\s+(humans?|people)|people\\s+and\\s+animals|man\\s+and\\s+beast)", "gi"), phrase: "humans and animals", alternatives: ["humans and non-human animals","humans and other animals","people and other animals"], reason: "False dichotomy — humans ARE animals. The phrasing reproduces the speciesist framing animal-liberation writing opposes. 'Humans and other animals' preserves the meaning accurately." },
  { regex: new RegExp("(pet|dog|cat|rabbit|bird)\\s+owners?", "gi"), phrase: "pet owner", alternatives: ["pet guardian","dog guardian","cat guardian","human companion"], reason: "Property framing — 'owner' treats sentient beings as possessions. 'Guardian' preserves the legal and caregiving relationship without the property connotation. Used in legal reform jurisdictions (e.g. Boulder CO, West Hollywood) since the early 2000s." },
  { regex: new RegExp("own(s|ing|ed)?\\s+a\\s+(pet|dog|cat|rabbit|bird)", "gi"), phrase: "own a pet", alternatives: ["live with a companion animal","share a home with","care for a"], reason: "Property framing applied to companion animals. 'Live with a dog' or 'share a home with a cat' captures the relationship without the ownership frame." },
  { regex: new RegExp("(fish|shrimp|salmon|tilapia)\\s+harvest(ing)?", "gi"), phrase: "fish harvest", alternatives: ["fish slaughter","shrimp slaughter","salmon slaughter"], reason: "Aquaculture euphemism for killing/slaughtering farmed fish/shrimp. 'Harvest' obscures the mass killing at the end of the grow-out phase." },
  { regex: new RegExp("stocking\\s+density(ies)?", "gi"), phrase: "stocking density", alternatives: ["crowding density","confinement density"], reason: "Industry term for extreme overcrowding in aquaculture tanks/ponds/net pens, where fish are packed at densities causing stress, disease, and cannibalism." },
  { regex: new RegExp("(harvest|market)\\s+size|slaughter\\s+weight", "gi"), phrase: "harvest size", alternatives: ["slaughter size","killing weight"], reason: "Euphemism for the size/weight at which farmed fish/shrimp are killed ('harvested')." },
  { regex: new RegExp("grow-out\\s+(pond|tank|phase)", "gi"), phrase: "grow-out pond", alternatives: ["fattening pond","fattening tank"], reason: "Final fattening phase before slaughter in aquaculture." },
];

export default async function noAnimalViolence(options: NoAnimalViolenceOptions = {}) {
  const report = options.severity === "message" ? message : warn;
  const modifiedFiles = danger.git.modified_files.concat(danger.git.created_files);

  const diffs = await Promise.all(modifiedFiles.map(f => danger.git.diffForFile(f)));
  for (let i = 0; i < modifiedFiles.length; i++) {
    const result = diffs[i];
    if (!result) continue;
    const file = modifiedFiles[i];
    const added = result.added;

    for (const pattern of PATTERNS) {
      if (pattern.regex.test(added)) {
        report(
          `**${file}**: Found "${pattern.phrase}". ${pattern.reason} ` +
          `Consider: ${pattern.alternatives.map(a => `"${a}"`).join(" or ")}. ` +
          `See https://github.com/Open-Paws/no-animal-violence for details.`
        );
        pattern.regex.lastIndex = 0;
      }
    }
  }
}
